### ISSUE TITLE
[Suggestion] Move from create-react-app

### ISSUE THREAD

**Issue by elianiva** [chrisdionisius/personal-portfolio#1]
Hi! I came across this repo recently and it seems like it's still new. I noticed that you use create-react-app which is actually deprecated a while ago. 

So, I would like to suggest you to use one of the [recommendations from the react.dev docs](https://react.dev/learn/start-a-new-react-project) instead since they provide better DX and UX for what you're trying to build. create-react-app can be a PITA sometimes.

Cheers! =)

**Comment by rahXephonz** [comment]
kak PITA itu apa? :"3

**Comment by elianiva** [comment]
> kak PITA itu apa? :"3

pain in the arse

**Comment by chrisdionisius** [comment]
Ah, yea thanks for the information, noted above
Next time I init a new project I'll use the proper way
really appreciate it 🍺
